import "./globals.css";
import type { Metadata } from "next";
import NavBar from "@/app/ui/NavBar";
import Footer from "@/app/ui/Footer";

export const metadata: Metadata = {
  title: "Handcrafted Haven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="font-sans antialiased min-h-screen flex flex-col bg-cream text-dark-brown">
        {/* --- HEADER --- */}
        <header className="border-b border-dark-brown/20 bg-light-green">
          <NavBar /> 
        </header>

        {/* --- MAIN CONTENT --- */}
        <main className="flex-grow">{children}</main>

        {/* --- FOOTER  --- */}
        <footer className="border-t border-dark-brown/20 bg-light-green">
          <Footer /> 
        </footer>
      </body>
    </html>
  );
}
